export const endpoints = {
  UserSignup: "/api/auth/signup",
  UserLogin: "/api/auth/login",
  Uploadpaper: "/api/upload-paper",
  Uploadimage: "/api/upload-image",
  Userdetails: "/api/user-details",
  Researchpaper: "/api/research-papers",
  Researchlinkusers: "/api/users",
  Sendrequest: "/api/send-request",
  Getrequest: "/api/get-request",
  Getuserprofile: "/api/user-profile",
  Useractivities: "/api/user-activities",
  Userstats: "/api/user-stats",
  Likes:'/api/likes',
  Dislikes:'/api/dislikes',
  Follow:'/api/followers',
  Deleteactivity:'/api/delete-activity',
  Editactivity:'/api/edit-activity',
};
